liip_imagine:
  driver: "gd"
  filter_sets:
    miniature:
      quality: 75
      filters:
        thumbnail:
          size: [600, 330]
          mode: outbound

    welcome:
          quality: 75
          filters:
            scale:
              dim: [700, 700]
    full:
      quality: 75
      filters:
        scale:
          dim: [ 650,650 ]

    portfolio:
        quality: 75
        filters:
          scale:
            dim: [ 400,400 ]
